# Generated by Django 4.2.27 on 2026-01-12 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0003_user_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vc_otp', models.CharField(max_length=20)),
                ('vc_start', models.DateTimeField()),
                ('vc_end', models.DateTimeField()),
                ('vc_status', models.BooleanField(default=False)),
                ('us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
