# Generated by Django 4.2.27 on 2026-02-27 00:00

from django.db import migrations, models


def set_lesson_kind(apps, schema_editor):
    Lesson = apps.get_model("courses", "Lesson")
    # Mark lessons that have children as groups
    group_ids = list(
        Lesson.objects
        .filter(children__isnull=False)
        .values_list("id", flat=True)
        .distinct()
    )
    Lesson.objects.filter(id__in=group_ids).update(kind="group")


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_lessontranslation_short_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="kind",
            field=models.CharField(
                choices=[("group", "Group"), ("lesson", "Lesson")],
                default="lesson",
                max_length=10,
            ),
        ),
        migrations.RunPython(set_lesson_kind, migrations.RunPython.noop),
    ]
