# Generated by Django 4.2.27 on 2025-12-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_alter_course_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
    ]
