# Generated by Django 5.0.9 on 2026-01-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_lessontranslation_delete_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessontranslation',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lessontranslation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
    ]
