# Generated by Django 4.2.27 on 2026-04-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0006_lessontranslation_short_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="kind",
            field=models.CharField(choices=[("group", "Group"), ("lesson", "Lesson")], default="lesson", max_length=10),
        ),
    ]

