# Generated by Django 4.2.27 on 2026-01-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'Lựa chọn', 'verbose_name_plural': 'Danh sách lựa chọn'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Câu hỏi', 'verbose_name_plural': 'Danh sách câu hỏi'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Bài kiểm tra', 'verbose_name_plural': 'Danh sách bài kiểm tra'},
        ),
    ]
