# Generated by Django 4.2.27 on 2026-03-21 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("join_code", models.CharField(max_length=8, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "teacher",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="teaching_classes", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("type", models.CharField(choices=[("QUIZ", "Quiz"), ("CODE", "Code")], max_length=10)),
                ("content", models.JSONField()),
                ("deadline", models.DateTimeField(blank=True, null=True)),
                (
                    "class_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="classes.class"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClassEnrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="enrollments", to="classes.class"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="class_enrollments", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("class_id", "student")},
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("submitted_content", models.JSONField()),
                ("score", models.FloatField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment_id",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="classes.assignment"),
                ),
                (
                    "student",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="assignment_submissions", to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
