# Generated by Django 4.2.27 on 2026-04-04 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
