# Generated by Django 4.2.27 on 2026-01-12 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Common', '0004_verification'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verification',
            table='verification',
        ),
    ]
