# Generated by Django 4.2.27 on 2026-04-04 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score", models.FloatField(default=0.0)),
                ("level", models.CharField(blank=True, max_length=50, null=True)),
                ("strengths", models.TextField(blank=True, null=True)),
                ("weaknesses", models.TextField(blank=True, null=True)),
                ("recommended_paths", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="test_result", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "test_results",
            },
        ),
    ]

